# Generated by Django 4.1.6 on 2023-02-11 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='категория')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=400, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='фотография')),
                ('text', models.CharField(max_length=50, verbose_name='заголовок')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='price')),
                ('status', models.CharField(choices=[('to_modern', 'на модерацию'), ('published', 'опубликовано'), ('rejected', 'отклонено'), ('to_delete', 'на удаление')], default='to_modern', max_length=20, verbose_name='статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='author_ad', to=settings.AUTH_USER_MODEL, verbose_name='Автор объявления')),
                ('category', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='webapp.category', verbose_name='цена')),
            ],
        ),
    ]
