# Generated by Django 4.1.6 on 2023-02-11 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='category',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='webapp.category', verbose_name='категория'),
        ),
    ]
