# Generated by Django 4.1.6 on 2023-02-11 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_ads_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='webapp.ads', verbose_name='объявление'),
            preserve_default=False,
        ),
    ]
