# Generated by Django 4.1.6 on 2023-02-11 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_comment_ad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ads',
            options={'permissions': [('choice_ads', 'Отбирать объявления')]},
        ),
    ]
