# Generated by Django 4.1.6 on 2023-02-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_ads_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='is_moderated',
            field=models.BooleanField(default=False, verbose_name='Подтвержден'),
        ),
    ]
